[project]
name = "uv"
version = "0.1.0"
description = "sample flask+uv project for container"
requires-python = ">=3.13"
dependencies = [
    "flask==3.0.2",
    "pytest==8.0.0",
    "python-dotenv==1.0.1",
    "requests==2.31.0",
]
